"""empty message

Revision ID: 9148bd4e481c
Revises: 
Create Date: 2021-09-01 22:16:08.221323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9148bd4e481c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Customers_first_name', table_name='Customers')
    op.drop_index('ix_Customers_id', table_name='Customers')
    op.drop_index('ix_Customers_last_name', table_name='Customers')
    op.drop_table('Customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('monthly_income', sa.FLOAT(), nullable=True),
    sa.Column('dob', sa.DATETIME(), nullable=True),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Customers_last_name', 'Customers', ['last_name'], unique=False)
    op.create_index('ix_Customers_id', 'Customers', ['id'], unique=False)
    op.create_index('ix_Customers_first_name', 'Customers', ['first_name'], unique=False)
    # ### end Alembic commands ###
